# Generated by Django 4.1.3 on 2022-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_amount_alter_account_current_bal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
